/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#bdc7d8',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f0f1f2',
        'error-container': '#ffdad6',
        'inverse-primary': '#6bd8cb',
        'outline': '#6d7a77',
        'secondary-fixed-dim': '#c0c6db',
        'on-primary-fixed': '#00201d',
        'background': '#f8f9fa',
        'tertiary': '#535d6b',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#404758',
        'surface-container-low': '#f3f4f5',
        'on-background': '#191c1d',
        'error': '#ba1a1a',
        'on-secondary': '#ffffff',
        'primary-container': '#008378',
        'tertiary-fixed': '#d9e3f4',
        'primary-fixed-dim': '#6bd8cb',
        'surface-dim': '#d9dadb',
        'secondary-fixed': '#dce2f7',
        'on-error-container': '#93000a',
        'surface-container-high': '#e7e8e9',
        'on-surface': '#191c1d',
        'surface': '#f8f9fa',
        'secondary': '#575e70',
        'outline-variant': '#bcc9c6',
        'surface-container': '#edeeef',
        'on-tertiary-fixed-variant': '#3e4755',
        'on-secondary-fixed': '#141b2b',
        'surface-container-highest': '#e1e3e4',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#2e3132',
        'surface-tint': '#006a61',
        'surface-bright': '#f8f9fa',
        'tertiary-container': '#6b7584',
        'on-tertiary-fixed': '#121c28',
        'on-primary-container': '#f4fffc',
        'primary': '#00685f',
        'on-tertiary-container': '#fdfcff',
        'on-primary-fixed-variant': '#005049',
        'secondary-container': '#d9dff5',
        'surface-variant': '#e1e3e4',
        'on-surface-variant': '#3d4947',
        'on-error': '#ffffff',
        'primary-fixed': '#89f5e7',
        'on-secondary-container': '#5c6274',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'padding-xs': '4px',
        'padding-sm': '8px',
        'padding-md': '16px',
        'padding-lg': '24px',
        'unit': '4px',
        'sidebar-width': '240px',
        'topbar-height': '56px',
        'container-margin': '24px',
        'gutter-md': '16px',
      },
      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'mono-label': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'mono-label': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      boxShadow: {
        soft: '0px 4px 6px -1px rgba(0,0,0,0.05), 0px 2px 4px -2px rgba(0,0,0,0.05)',
      },
    },
  },
  plugins: [],
};